[webservers]
web-1 ansible_host=111.88.247.205 fqdn=fhm1kk4ehctjjbotra5u.auto.internal
web-2 ansible_host=51.250.9.210 fqdn=fhmpg4943ulaabvb0e5c.auto.internal

[databases]
main ansible_host=93.77.190.204 fqdn=fhmk2vvvj1o6d0j3rt5h.auto.internal
replica ansible_host=111.88.250.229 fqdn=fhmfthgg176abbvccrfg.auto.internal

[storage]
storage ansible_host=158.160.52.72 fqdn=fhmkiroe4boiut76srh4.auto.internal
